project:
  type: website

website:
  title: "Bernd Funovits"
  navbar:
    search: true
    tools:
      - icon: github
        url: http://www.github.com/bfunovits
  sidebar:
    collapse-level: 1
    style: "docked"
    contents:
      - text: "About"
        file: index.qmd
      - projects_professional.qmd
      - section: "CV"
        file: cv_index.qmd
        contents:
          - cv_long.qmd
          - cv_latex.qmd
      - section: "Academia"
        file: academia.qmd
        contents:
          - research_abstracts.qmd
          - section: "Research Papers"
            file: research_papers.qmd
            contents:
              - research_papers_blaschke.qmd
              - research_papers_gmr.qmd
      - text: "Personal Projects"
        file: projects_misc.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



