project:
  type: website

website:
  title: "Bernd Funovits"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Professional Projects"
        contents:
          - projects_professional.qmd
      - section: "CV"
        contents:
          - cv_index.qmd
          - cv_long.qmd
          - cv_latex.qmd
      - section: "Academia"
        contents:
          - academia.qmd
          - research_abstracts.qmd
      - section: "Research Papers"
        contents:
          - research_papers.qmd
          - research_papers_blaschke.qmd
          - research_papers_gmr.qmd
      - section: "Personal Projects"
        contents:
          - projects_misc.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



